### ISSUE TITLE
corpusProcess.sh with other corpus file

### ISSUE THREAD

**Issue by PxYu** [mickeystroller/SetExpan#4]
Hi, i am encountering some issues that are somewhat similar with [a previous issue](https://github.com/mickeystroller/SetExpan/issues/2).

Q1: The corpusProcess.sh call two scripts from AutoPhrase (auto_phrase.sh and phrasal_segmentation.sh). Is the former one necessary? 

Q2: phrasal_segmentation.sh takes 4 arguments from input, while corpusProcess.sh only provides 3. What is the meaning of "TEXT_TO_SEG" from phrasal_segmentation.sh?

Thank you!

**Comment by mickeysjm** [comment]
Hi PxYu,

For Q1, both of them are necessary. The auto_phrase.sh will generate a list of quality phrases (based on which we will generate the vocabulary file), and the phrasal_segmentation.sh will generate the in-corpus mentions of those phrases.

For Q2, such mismatch is due to the update of AutoPhrase toolkit (after I upload this repo). These are two ways to solve it. One is to replace the original phrasal_segmentation.sh with the one in https://github.com/mickeystroller/SetExpan/tree/master/src/tools/AutoPhrase/. Another way (which I will recommend) is to directly use the data preprocessing pipeline in HiExpan https://github.com/mickeystroller/HiExpan/blob/master/src/corpusProcessing/corpusProcess_new.sh. This is an end-to-end pipeline will take care all the data preprocessing. 

Thanks,
--Jiaming

**Comment by PxYu** [comment]
@mickeystroller thank you for the detailed explanation.
